name: Integration Test
run-name: Testing `${{ inputs.rascal_branch_build }}` (Rascal) with ${{ case(inputs.typepal_branch_build != '', format('`{0}`', inputs.typepal_branch_build), 'version in pom.xml') }} (Typepal)
on:
  workflow_dispatch:
    inputs:
      rascal_branch_build:
        description: 'rascal branch/tag to build jar'
        required: true
        default: 'main'

      typepal_branch_build:
        description: 'typepal branch/tag to build jar. Default: version in pom.xml.'
        required: false

      rascal_branch_check:
        description: 'rascal branch/tag to be typechecked (standard library). Default: `main`.'
        required: false

      typepal_branch_check:
        description: 'typepal branch/tag to be typechecked. Default: `main`.'
        required: false

      rascal_lsp_all_branch_check:
        description: 'rascal-lsp-all branch/tag to be typechecked. Default: `main`.'
        default: 'main'
        required: true

      dependencies_on_lib_path:
        description: 'Put tpls of dependencies on lib path'
        required: true
        default: 'true'

      also_check_compiler:
        description: 'Run the typechecker on the compiler'
        required: true
        default: 'true'
      do_package:
        description: 'Run the packager'
        required: true
        default: 'true'

env:
  MAVEN_OPTS: "-Xmx4G -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  IS_OWN_PR: "${{ secrets.MAVEN_MIRROR_URL }}"

jobs:
  test:
    runs-on: ubicloud-standard-4
    strategy:
      matrix:
        target:
          - "'rascal-stdlib' 'flybytes' 'salix-core' 'salix-contrib' 'drambiguity' 'rascal-lsp' 'rascal-git' 'php-analysis' 'typepal' 'clair' 'java-air' 'python-air' 'rascal-lucene'"
          - "'typepal-copy' 'rascal-all' 'rascal-lsp-all'"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout rascal (${{ inputs.rascal_branch_build }})'
        with:
          repository: 'usethesource/rascal'
          ref: ${{ inputs.rascal_branch_build }}
          path: 'deps/rascal'

      - uses: actions/checkout@v4
        if: ${{ inputs.typepal_branch_build != '' }}
        name: 'Checkout typepal (${{ inputs.typepal_branch_build }})'
        with:
          repository: 'usethesource/typepal'
          ref: ${{ inputs.typepal_branch_build }}
          path: 'deps/typepal'

      - uses: s4u/maven-settings-action@v3.1.0
        if: ${{ env.IS_OWN_PR != '' }}
        with:
          servers: '[{"id": "usethesource-gh", "username":"github", "password": "${{ secrets.MAVEN_MIRROR_PASSWORD }}"}]'
          mirrors: '[{"id": "usethesource-gh", "name": "uts mirror", "mirrorOf": "usethesource", "url": "${{ secrets.MAVEN_MIRROR_URL }}"}]'

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'deps/rascal/pom.xml'

      # If a Typepal branch/tag to build `rascal.jar` **isn't** provided, then
      # the following three steps are skipped, and a Typepal dependency version
      # is installed and used based on Rascal's `pom.xml`. If it **is**
      # provided, then that branch/tag is installed. To ensure it is also used,
      # Rascal's `pom.xml` needs to be updated to refer to the installed Typepal
      # dependency version (otherwise, silently, the dependency version in
      # Rascal's `pom.xml` is still used).

      - name: Install typepal dependency version to build jar (overriding pom.xml)
        if: ${{ inputs.typepal_branch_build != '' }}
        run: mvn -B install -Drascal.tutor.skip -DskipTests -Drascal.compile.skip -Drascal.package.skip
        working-directory: deps/typepal

      - name: Read typepal dependency version to build jar (overriding pom.xml)
        if: ${{ inputs.typepal_branch_build != '' }}
        id: read-typepal-dep-version
        run: echo "typepal_dep_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
        working-directory: deps/typepal

      - name: Write typepal dependency version to build jar (overriding pom.xml)
        # In most cases, this step isn't needed as pom.xml normally points to
        # the intended dependency version of Typepal already. A case when it
        # could be useful is to test the effect of new changes in a non-`main`
        # branch of Typepal on Rascal before merging it into `main`.
        if: ${{ inputs.typepal_branch_build != '' }}
        run: |
          mvn -B versions:use-dep-version \
            -Dincludes=org.rascalmpl:typepal \
            -DdepVersion=${{ steps.read-typepal-dep-version.outputs.typepal_dep_version }} \
            -DforceVersion=true
        working-directory: deps/rascal

      - name: Set rascal branch to be typechecked (overriding default)
        if: ${{ inputs.rascal_branch_check != ''}}
        run: echo "RASCAL_BRANCH=${{ inputs.rascal_branch_check }}" >> "$GITHUB_ENV"

      - name: Set typepal branch to be typechecked (overriding default)
        if: ${{ inputs.typepal_branch_check != ''}}
        run: echo "TYPEPAL_BRANCH=${{ inputs.typepal_branch_check }}" >> "$GITHUB_ENV"

      - name: Set rascal branch to be typechecked in the ...-all tests
        # A Rascal branch/tag to build `rascal.jar` **is** provided, so no
        # conditional is needed here.
        run: echo "RASCAL_ALL_BRANCH=${{ inputs.rascal_branch_build }}" >> "$GITHUB_ENV"

      - name: Set typepal branch to be typechecked in the ...-all tests
        if: ${{ inputs.typepal_branch_build == ''}}
        # If a Typepal branch/tag to build `rascal.jar` **isn't** provided, then
        # a Typepal dependency version has been installed and used based on
        # Rascal's `pom.xml`. To typecheck the same version in the ...-all
        # tests, that version needs to be read in Rascal's `pom.xml`.
        run: |
          version=$(mvn dependency:list | grep typepal | sed 's/.*org.rascalmpl:typepal:jar:\(.*\):.*/\1/')
          echo "TYPEPAL_COPY_BRANCH=v$version" >> "$GITHUB_ENV"
        working-directory: deps/rascal

      - name: Set typepal branch to be typechecked in the ...-all tests (overriding default)
        if: ${{ inputs.typepal_branch_build != ''}}
        run: echo "TYPEPAL_COPY_BRANCH=${{ inputs.typepal_branch_build }}" >> "$GITHUB_ENV"

      - name: Compile rascal java
        run: mvn -B clean compile package -Drascal.tutor.skip -DskipTests -Drascal.compile.skip -Drascal.package.skip
        working-directory: deps/rascal

      - name: copy rascal jar to predictable location and cleanup
        run: |
          rm deps/rascal/target/*-sources.jar
          find deps/rascal/target -maxdepth 1 -name 'rascal-*.jar' -exec mv '{}' ${{ runner.temp }}/rascal.jar \;
          rm -rf deps

      - name: Checkout integration-script
        uses: actions/checkout@v4

      - name: Typecheck
        if: ${{ !contains(matrix.target, 'rascal-all') || inputs.also_check_compiler }}
        env:
          JAVA_TOOL_OPTIONS: "-Djava.io.tmpdir=${{ runner.temp }}"
          RASCAL_LSP_ALL_BRANCH: "${{ inputs.rascal_lsp_all_branch_check }}"
        run: |
          java -Xmx500m -jar ${{ runner.temp }}/rascal.jar Main \
            --libs "${{ inputs.dependencies_on_lib_path }}" \
            --maxCores 4 \
            --memory 12G \
            --rascalJar "|file:///${{ runner.temp }}/rascal.jar|" \
            --repoFolder "|cwd:///repos|" \
            --full false \
            --clean \
            --package "${{inputs.do_package}}" \
            --tests ${{ matrix.target }}
